import { Link } from 'react-router-dom'
import LegalLayout from '../components/LegalLayout'

const CONTACT = 'legal@scamshield.example'

const sections = [
  {
    id: 'acceptance',
    title: 'Agreement',
    body: (
      <p>
        By using ScamShield you agree to these terms and to our <Link to="/privacy">privacy policy</Link>. If you don’t agree, please don’t use the
        service.
      </p>
    ),
  },
  {
    id: 'service',
    title: 'What ScamShield is',
    body: (
      <>
        <p>
          ScamShield is a tool that helps you spot common warning signs in messages, links and payment requests. Results are generated by
          transparent, <strong>rule-based checks</strong> — not by a trained AI model — and every result lists the signals that produced it.
        </p>
        <p>ScamShield is not affiliated with any bank, payment app, telecom operator or government body.</p>
      </>
    ),
  },
  {
    id: 'accuracy',
    title: 'Results are guidance, not a guarantee',
    body: (
      <>
        <ul>
          <li>A “Safe” result doesn’t mean something is legitimate, and a “Dangerous” result doesn’t prove fraud.</li>
          <li>The risk score is a 0–100 index based on the signals found. It is not a probability or a confidence percentage.</li>
          <li>Scammers change tactics constantly, so some scams won’t be detected and some genuine messages may be flagged.</li>
        </ul>
        <p>Always use your own judgement and verify through official channels before acting.</p>
      </>
    ),
  },
  {
    id: 'advice',
    title: 'Not professional advice',
    body: (
      <p>
        Nothing in ScamShield is financial, legal or professional security advice. If you think you’ve lost money, contact your bank and call the
        national cyber-fraud helpline on 1930 or file a complaint at <a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer noopener">cybercrime.gov.in</a>.
      </p>
    ),
  },
  {
    id: 'use',
    title: 'Acceptable use',
    body: (
      <>
        <p>You agree not to:</p>
        <ul>
          <li>submit reports you know to be false, or use reports to harass or defame anyone;</li>
          <li>submit other people’s sensitive personal data beyond what’s needed to describe a scam;</li>
          <li>attempt to overload, reverse-engineer, scrape or disrupt the service;</li>
          <li>use ScamShield to test or improve scams.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'reports',
    title: 'Content you submit',
    body: (
      <p>
        You keep ownership of what you submit. By submitting a report you allow ScamShield to store, analyse and — once the community database is
        live — publish it without your identity, to help warn others. We may edit or remove reports that are inaccurate, abusive or contain personal
        data.
      </p>
    ),
  },
  {
    id: 'links',
    title: 'Third-party links',
    body: <p>We link to official resources such as government helplines. We aren’t responsible for the content or availability of those sites.</p>,
  },
  {
    id: 'ip',
    title: 'Intellectual property',
    body: <p>The ScamShield name, logo, interface and software are owned by the ScamShield team. You may not copy or reuse them without permission.</p>,
  },
  {
    id: 'liability',
    title: 'Limitation of liability',
    body: (
      <p>
        ScamShield is provided “as is”. To the extent permitted by law, we aren’t liable for any loss arising from decisions you make based on a
        result, including money lost to a scam that wasn’t detected. Nothing in these terms limits liability that can’t be limited under applicable
        law.
      </p>
    ),
  },
  {
    id: 'changes',
    title: 'Changes and termination',
    body: (
      <p>
        We may update these terms as the product develops, and will change the date above when we do. We may suspend access for anyone who breaks
        these terms.
      </p>
    ),
  },
  {
    id: 'law',
    title: 'Governing law',
    body: <p>These terms are governed by the laws of India. Disputes are subject to the jurisdiction of the competent courts in India.</p>,
  },
  {
    id: 'contact',
    title: 'Contact',
    body: (
      <p>
        Questions about these terms: <a href={`mailto:${CONTACT}`}>{CONTACT}</a>.
      </p>
    ),
  },
]

export default function Terms() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Terms & conditions"
      updated="26 September 2026"
      intro="These terms set out how you can use ScamShield and what you can expect from it. The most important point: ScamShield helps you spot warning signs, but the final decision is always yours."
      sections={sections}
      other={{ to: '/privacy', label: 'Privacy policy' }}
    />
  )
}
